services:
  redis:
    image: redis:7-alpine
    container_name: periodico_redis
    expose:
      - "6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: periodico_backend
    volumes:
      - ./backend:/app
      - ./Amazonia-landing:/Amazonia-landing
      - django_static:/var/www/static
      - C:\var\www\media:/var/www/media
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    ports:
      - "8000:8000"

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: periodico_celery_worker
    volumes:
      - ./backend:/app
      - C:\var\www\media:/var/www/media
    env_file:
      - .env
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
      - backend

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: periodico_celery_beat
    volumes:
      - ./backend:/app
      - C:\var\www\media:/var/www/media
    env_file:
      - .env
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
      - backend

volumes:
  django_static:
