class AuditoriaModulo:
    M01 = 'M01'
    M02 = 'M02'  # accounts / auth
    M03 = 'M03'
    M04 = 'M04'
    M05 = 'M05'
    M06 = 'M06'
    M07 = 'M07'
    M08 = 'M08'
    M09 = 'M09'
    M10 = 'M10'
    M11 = 'M11'
    M12 = 'M12'

    CHOICES = [
        (M01, 'M01'),
        (M02, 'M02'),
        (M03, 'M03'),
        (M04, 'M04'),
        (M05, 'M05'),
        (M06, 'M06'),
        (M07, 'M07'),
        (M08, 'M08'),
        (M09, 'M09'),
        (M10, 'M10'),
        (M11, 'M11'),
        (M12, 'M12'),
    ]


class AuditoriaResultado:
    EXITOSO = 'EXITOSO'
    RECHAZADO = 'RECHAZADO'
    ERROR = 'ERROR'

    CHOICES = [
        (EXITOSO, 'EXITOSO'),
        (RECHAZADO, 'RECHAZADO'),
        (ERROR, 'ERROR'),
    ]


class AuditoriaAccion:
    REGISTRO_USUARIO = 'REGISTRO_USUARIO'
    VERIFICACION_CORREO_EXITOSA = 'VERIFICACION_CORREO_EXITOSA'
    VERIFICACION_CORREO_FALLIDA = 'VERIFICACION_CORREO_FALLIDA'
    TOKEN_VERIFICACION_VENCIDO = 'TOKEN_VERIFICACION_VENCIDO'
    TOKEN_VERIFICACION_REUTILIZADO = 'TOKEN_VERIFICACION_REUTILIZADO'
    REENVIO_VERIFICACION_SOLICITADO = 'REENVIO_VERIFICACION_SOLICITADO'
    REENVIO_VERIFICACION_ENVIADO = 'REENVIO_VERIFICACION_ENVIADO'
    REENVIO_VERIFICACION_LIMITADO = 'REENVIO_VERIFICACION_LIMITADO'
    REENVIO_VERIFICACION_IGNORADO = 'REENVIO_VERIFICACION_IGNORADO'
    LOGIN_EXITOSO = 'LOGIN_EXITOSO'
    LOGIN_FALLIDO = 'LOGIN_FALLIDO'
    CUENTA_BLOQUEADA = 'CUENTA_BLOQUEADA'
    TOKEN_REFRESH_EXITOSO = 'TOKEN_REFRESH_EXITOSO'
    TOKEN_REFRESH_RECHAZADO = 'TOKEN_REFRESH_RECHAZADO'
    LOGOUT_EXITOSO = 'LOGOUT_EXITOSO'
    SESION_REVOCADA = 'SESION_REVOCADA'
    ACCESO_CON_SESION_INVALIDA = 'ACCESO_CON_SESION_INVALIDA'
    EMPRESA_CREADA = 'EMPRESA_CREADA'
    EMPRESA_ACTUALIZADA = 'EMPRESA_ACTUALIZADA'
    IDENTIDAD_EMPRESA_ACTUALIZADA = 'IDENTIDAD_EMPRESA_ACTUALIZADA'
    CONFIGURACION_EMPRESA_ACTUALIZADA = 'CONFIGURACION_EMPRESA_ACTUALIZADA'
    ACCESO_EMPRESA_DENEGADO = 'ACCESO_EMPRESA_DENEGADO'
    PLAN_EMPRESA_CAMBIADO = 'PLAN_EMPRESA_CAMBIADO'
    PLAN_LIMITE_ALCANZADO = 'PLAN_LIMITE_ALCANZADO'
    FUNCIONALIDAD_PLAN_DENEGADA = 'FUNCIONALIDAD_PLAN_DENEGADA'
    PLAN_EXPIRADO_DETECTADO = 'PLAN_EXPIRADO_DETECTADO'
    CAMBIO_PLAN_CON_SOBRECONSUMO = 'CAMBIO_PLAN_CON_SOBRECONSUMO'

    # Ediciones
    EDICION_CREADA = 'EDICION_CREADA'
    EDICION_ACTUALIZADA = 'EDICION_ACTUALIZADA'
    EDICION_PROGRAMADA = 'EDICION_PROGRAMADA'
    EDICION_PUBLICADA = 'EDICION_PUBLICADA'
    EDICION_SUSPENDIDA = 'EDICION_SUSPENDIDA'
    EDICION_REACTIVADA = 'EDICION_REACTIVADA'
    PUBLICACION_RECHAZADA_NO_PROCESADA = 'PUBLICACION_RECHAZADA_NO_PROCESADA'
    LIMITE_EDICIONES_ALCANZADO = 'LIMITE_EDICIONES_ALCANZADO'
    ACCESO_EDICION_DENEGADO = 'ACCESO_EDICION_DENEGADO'
    EDICION_PDF_CARGADO = 'EDICION_PDF_CARGADO'
    PROCESAMIENTO_INICIADO = 'PROCESAMIENTO_INICIADO'
    PROCESAMIENTO_COMPLETADO = 'PROCESAMIENTO_COMPLETADO'
    PROCESAMIENTO_FALLIDO = 'PROCESAMIENTO_FALLIDO'
    PROCESAMIENTO_CANCELADO = 'PROCESAMIENTO_CANCELADO'
    PROCESAMIENTO_REINTENTADO = 'PROCESAMIENTO_REINTENTADO'




