class EstadoEdicion:
    BORRADOR = 'BORRADOR'
    PENDIENTE_PROCESAMIENTO = 'PENDIENTE_PROCESAMIENTO'
    PROCESANDO = 'PROCESANDO'
    PROCESADA = 'PROCESADA'
    PROGRAMADA = 'PROGRAMADA'
    PUBLICADA = 'PUBLICADA'
    SUSPENDIDA = 'SUSPENDIDA'
    INACTIVA = 'INACTIVA'
    ERROR = 'ERROR'

    ALL = [
        BORRADOR, PENDIENTE_PROCESAMIENTO, PROCESANDO, PROCESADA,
        PROGRAMADA, PUBLICADA, SUSPENDIDA, INACTIVA, ERROR
    ]


class EventoEdicionHistorial:
    CREACION = 'CREACION'
    EDICION_DATOS = 'EDICION_DATOS'
    CAMBIO_PRECIO = 'CAMBIO_PRECIO'
    CARGA_PORTADA = 'CARGA_PORTADA'
    CARGA_PDF = 'CARGA_PDF'
    REEMPLAZO_ARCHIVO = 'REEMPLAZO_ARCHIVO'
    SOLICITUD_PROCESAMIENTO = 'SOLICITUD_PROCESAMIENTO'
    PROCESAMIENTO_COMPLETADO = 'PROCESAMIENTO_COMPLETADO'
    PROCESAMIENTO_ERROR = 'PROCESAMIENTO_ERROR'
    PROGRAMACION = 'PROGRAMACION'
    CANCELACION_PROGRAMACION = 'CANCELACION_PROGRAMACION'
    PUBLICACION = 'PUBLICACION'
    SUSPENSION = 'SUSPENSION'
    REACTIVACION = 'REACTIVACION'
    DESACTIVACION = 'DESACTIVACION'


# Valid transition state map: key is the current state, value is a set/list of allowed next states.
VALID_TRANSITIONS = {
    EstadoEdicion.BORRADOR: {EstadoEdicion.PENDIENTE_PROCESAMIENTO},
    EstadoEdicion.PENDIENTE_PROCESAMIENTO: {EstadoEdicion.PROCESANDO, EstadoEdicion.ERROR},
    EstadoEdicion.PROCESANDO: {EstadoEdicion.PROCESADA, EstadoEdicion.ERROR},
    EstadoEdicion.PROCESADA: {EstadoEdicion.PROGRAMADA, EstadoEdicion.PUBLICADA},
    EstadoEdicion.PROGRAMADA: {EstadoEdicion.PUBLICADA, EstadoEdicion.BORRADOR},
    EstadoEdicion.PUBLICADA: {EstadoEdicion.SUSPENDIDA},
    EstadoEdicion.SUSPENDIDA: {EstadoEdicion.PUBLICADA, EstadoEdicion.BORRADOR},
}


# Fields that are NOT allowed to be modified if the edition is in PUBLICADA state
UNEDITABLE_FIELDS_WHEN_PUBLISHED = {
    'codigo',
    'fecha_edicion',
    'modalidad',
    'precio',
    'moneda',
    'slug',
}
